export const CERTBOT_ENV_LIST = [
  "CERTBOT_DOMAIN",
  "CERTBOT_VALIDATION",
  "CERTBOT_TOKEN",
  "CERTBOT_CERT_PATH",
  "CERTBOT_KEY_PATH",
  "CERTBOT_SNI_DOMAIN",
  "CERTBOT_AUTH_OUTPUT",
  "EDIT_CMD",
];
